apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-starter-mac-app
  labels:
    app: django-starter-mac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-starter-mac
  template:
    metadata:
      labels:
        app: django-starter-mac
    spec:
      imagePullSecrets:
        - name: harbor-registry-secret
      containers:
        - image: harbor.arpansahu.me/library/django_starter_mac:latest
          name: django-starter-mac
          name: django-starter-mac
          envFrom:
            - secretRef:
                name: django-starter-secret
          ports:
            - containerPort: 8016
              name: gunicorn