apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-starter-mac-app
  labels:
    app: django-starter-mac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-starter-mac
  template:
    metadata:
      labels:
        app: django-starter-mac
    spec:
      imagePullSecrets:
        - name: harbor-registry-secret
      containers:
        - image: harbor.arpansahu.me/library/django_starter_mac:latest
          name: django-starter-mac
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-starter-secret
                  key: SECRET_KEY
            - name: DEBUG
              valueFrom:
                secretKeyRef:
                  name: django-starter-secret
                  key: DEBUG
            - name: ALLOWED_HOSTS
              valueFrom:
                secretKeyRef:
                  name: django-starter-secret
                  key: ALLOWED_HOSTS
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: django-starter-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: django-starter-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_STORAGE_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: django-starter-secret
                  key: AWS_STORAGE_BUCKET_NAME
            - name: BUCKET_TYPE
              valueFrom:
                secretKeyRef:
                  name: django-starter-secret
                  key: BUCKET_TYPE
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: django-starter-secret
                  key: DATABASE_URL
            - name: REDISCLOUD_URL
              valueFrom:
                secretKeyRef:
                  name: django-starter-secret
                  key: REDISCLOUD_URL
            - name: MAIL_JET_API_KEY
              valueFrom:
                secretKeyRef:
                  name: django-starter-secret
                  key: MAIL_JET_API_KEY
            - name: MAIL_JET_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: django-starter-secret
                  key: MAIL_JET_API_SECRET
            - name: MAIL_JET_EMAIL_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: django-starter-secret
                  key: MAIL_JET_EMAIL_ADDRESS
            - name: DOMAIN
              valueFrom:
                secretKeyRef:
                  name: django-starter-secret
                  key: DOMAIN
            - name: PROTOCOL
              valueFrom:
                secretKeyRef:
                  name: django-starter-secret
                  key: PROTOCOL
          ports:
            - containerPort: 8016
              name: gunicorn