apiVersion: v1
kind: Service
metadata:
  name: django-starter-service
spec:
  selector:
    app: django-starter
  ports:
    - protocol: TCP
      port: 8016
      targetPort: 8016
      nodePort: 32016
  type: NodePort