apiVersion: v1
kind: Service
metadata:
  name: django-starter-service
spec:
  selector:
    app: django-starter
  ports:
    - protocol: TCP
      port: 8016
      targetPort: 8016
      nodePort: 32016
    - name: celery-flower
      protocol: TCP
      port: 8054
      targetPort: 8054
      nodePort: 32054
  type: NodePort