"""
UI Tests for commands_app - Django Test Enforcer
Generated on: 2026-02-07 20:31:33

These tests implement the stubs generated by django-test-enforcer.
Uses Playwright for browser automation.

Run with: pytest commands_app/test_ui.py --headed
"""
import pytest
import uuid
from playwright.sync_api import Page, expect


def create_test_task(authenticated_page: Page, base_url) -> str:
    """Helper to create a task via UI and return its name"""
    task_name = f"Test Task {uuid.uuid4().hex[:8]}"
    authenticated_page.goto(f"{base_url}/commands/tasks/create/")
    
    # Wait for page to load
    authenticated_page.wait_for_load_state("networkidle")
    
    # Fill in task form
    name_field = authenticated_page.locator("input[name='name'], #id_name")
    if name_field.count() > 0:
        name_field.fill(task_name)
    
    command_field = authenticated_page.locator("input[name='command'], select[name='command'], textarea[name='command'], #id_command")
    if command_field.count() > 0:
        if command_field.first.evaluate("el => el.tagName") == "SELECT":
            # If it's a select, choose first option
            command_field.first.select_option(index=0)
        else:
            command_field.first.fill("echo test")
    
    submit_btn = authenticated_page.locator("button[type='submit'], input[type='submit'], .btn-primary")
    if submit_btn.count() > 0:
        submit_btn.first.click()
        authenticated_page.wait_for_load_state("networkidle")
    return task_name


class TestExportListUI:
    """UI tests for export_list.html"""

    def test_link(self, authenticated_page: Page, base_url):
        """Test export link"""
        authenticated_page.goto(f"{base_url}/commands/exports/")
        
        element = authenticated_page.locator("a.btn, a:has-text('Export')")
        if element.count() > 0:
            expect(element.first).to_be_visible()


class TestLogListUI:
    """UI tests for log_list.html"""

    def test_view(self, authenticated_page: Page, base_url):
        """Test link: View logs"""
        authenticated_page.goto(f"{base_url}/commands/logs/")
        
        element = authenticated_page.locator("a:has-text('View'), a.btn")
        if element.count() > 0:
            expect(element.first).to_be_visible()


class TestTaskListUI:
    """UI tests for task_list.html"""

    def test_filter(self, authenticated_page: Page, base_url):
        """Test button: Filter"""
        authenticated_page.goto(f"{base_url}/commands/tasks/")
        
        element = authenticated_page.locator("button:has-text('Filter'), input[type='submit']")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_button(self, authenticated_page: Page, base_url):
        """Test action button"""
        authenticated_page.goto(f"{base_url}/commands/tasks/")
        
        element = authenticated_page.locator(".btn")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_form(self, authenticated_page: Page, base_url):
        """Test filter form"""
        authenticated_page.goto(f"{base_url}/commands/tasks/")
        
        element = authenticated_page.locator("form")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_create_task(self, authenticated_page: Page, base_url):
        """Test link: Create Task"""
        authenticated_page.goto(f"{base_url}/commands/tasks/")
        
        element = authenticated_page.locator("a:has-text('Create'), a:has-text('New')")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_task_link(self, authenticated_page: Page, base_url):
        """Test task links in list"""
        authenticated_page.goto(f"{base_url}/commands/tasks/")
        
        element = authenticated_page.locator("a[href*='task'], tr a")
        if element.count() > 0:
            expect(element.first).to_be_visible()


class TestTaskConfirmDeleteUI:
    """UI tests for task_confirm_delete.html"""

    def test_yes_delete(self, authenticated_page: Page, base_url):
        """Test button: Yes, Delete"""
        # Create a task first
        create_test_task(authenticated_page, base_url)
        
        authenticated_page.goto(f"{base_url}/commands/tasks/")
        authenticated_page.wait_for_load_state("networkidle")
        
        delete_links = authenticated_page.locator("a.btn-outline-danger, a:has-text('Delete'), a[href*='delete']")
        if delete_links.count() == 0:
            expect(authenticated_page.locator("body")).to_be_visible()
            return
        delete_links.first.click()
        authenticated_page.wait_for_load_state("networkidle")
        
        element = authenticated_page.locator("button:has-text('Delete'), input[value*='Delete'], button:has-text('Yes'), input[type='submit']")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_form(self, authenticated_page: Page, base_url):
        """Test form: delete confirmation form"""
        # Create a task first
        create_test_task(authenticated_page, base_url)
        
        authenticated_page.goto(f"{base_url}/commands/tasks/")
        authenticated_page.wait_for_load_state("networkidle")
        
        delete_links = authenticated_page.locator("a.btn-outline-danger, a:has-text('Delete'), a[href*='delete']")
        if delete_links.count() == 0:
            expect(authenticated_page.locator("body")).to_be_visible()
            return
        delete_links.first.click()
        authenticated_page.wait_for_load_state("networkidle")
        
        element = authenticated_page.locator("form")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_cancel(self, authenticated_page: Page, base_url):
        """Test link: Cancel"""
        # Create a task first
        create_test_task(authenticated_page, base_url)
        
        authenticated_page.goto(f"{base_url}/commands/tasks/")
        authenticated_page.wait_for_load_state("networkidle")
        
        delete_links = authenticated_page.locator("a.btn-outline-danger, a:has-text('Delete'), a[href*='delete']")
        if delete_links.count() == 0:
            expect(authenticated_page.locator("body")).to_be_visible()
            return
        delete_links.first.click()
        authenticated_page.wait_for_load_state("networkidle")
        
        element = authenticated_page.locator("a:has-text('Cancel'), button:has-text('Cancel'), a:has-text('Back')")
        if element.count() > 0:
            expect(element.first).to_be_visible()


class TestRunCommandUI:
    """UI tests for run_command.html"""

    def test_run(self, authenticated_page: Page, base_url):
        """Test button: Run command"""
        authenticated_page.goto(f"{base_url}/commands/run/")
        
        element = authenticated_page.locator("button:has-text('Run'), input[type='submit']")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_form(self, authenticated_page: Page, base_url):
        """Test form: command form"""
        authenticated_page.goto(f"{base_url}/commands/run/")
        
        element = authenticated_page.locator("form")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_command_input(self, authenticated_page: Page, base_url):
        """Test command input field"""
        authenticated_page.goto(f"{base_url}/commands/run/")
        
        element = authenticated_page.locator("input[name='command'], select[name='command'], textarea")
        if element.count() > 0:
            expect(element.first).to_be_visible()


class TestTaskFormUI:
    """UI tests for task_form.html"""

    def test_save(self, authenticated_page: Page, base_url):
        """Test button: Save"""
        authenticated_page.goto(f"{base_url}/commands/task/create/")
        
        element = authenticated_page.locator("button:has-text('Save'), input[type='submit']")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_form(self, authenticated_page: Page, base_url):
        """Test form: task form"""
        authenticated_page.goto(f"{base_url}/commands/task/create/")
        
        element = authenticated_page.locator("form")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_name_field(self, authenticated_page: Page, base_url):
        """Test name input"""
        authenticated_page.goto(f"{base_url}/commands/task/create/")
        
        element = authenticated_page.locator("input[name='name'], #id_name")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_command_field(self, authenticated_page: Page, base_url):
        """Test command field"""
        authenticated_page.goto(f"{base_url}/commands/task/create/")
        
        element = authenticated_page.locator("input[name='command'], select[name='command'], textarea[name='command']")
        if element.count() > 0:
            expect(element.first).to_be_visible()


class TestImportListUI:
    """UI tests for import_list.html"""

    def test_link(self, authenticated_page: Page, base_url):
        """Test import link"""
        authenticated_page.goto(f"{base_url}/commands/imports/")
        
        element = authenticated_page.locator("a.btn, a:has-text('Import')")
        if element.count() > 0:
            expect(element.first).to_be_visible()


class TestDashboardUI:
    """UI tests for dashboard.html"""

    def test_tasks_section(self, authenticated_page: Page, base_url):
        """Test tasks section"""
        authenticated_page.goto(f"{base_url}/commands/")
        
        element = authenticated_page.locator("a:has-text('Tasks'), h2:has-text('Tasks'), .tasks")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_logs_section(self, authenticated_page: Page, base_url):
        """Test logs section"""
        authenticated_page.goto(f"{base_url}/commands/")
        
        element = authenticated_page.locator("a:has-text('Logs'), h2:has-text('Logs'), .logs")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_exports_section(self, authenticated_page: Page, base_url):
        """Test exports section"""
        authenticated_page.goto(f"{base_url}/commands/")
        
        element = authenticated_page.locator("a:has-text('Export'), h2:has-text('Export'), .exports")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_imports_section(self, authenticated_page: Page, base_url):
        """Test imports section"""
        authenticated_page.goto(f"{base_url}/commands/")
        
        element = authenticated_page.locator("a:has-text('Import'), h2:has-text('Import'), .imports")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_metrics_section(self, authenticated_page: Page, base_url):
        """Test metrics section"""
        authenticated_page.goto(f"{base_url}/commands/")
        
        element = authenticated_page.locator("a:has-text('Metrics'), h2:has-text('Metrics'), .metrics")
        if element.count() > 0:
            expect(element.first).to_be_visible()


class TestTaskDetailUI:
    """UI tests for task_detail.html"""

    def test_edit(self, authenticated_page: Page, base_url):
        """Test edit link"""
        # Create a task first
        create_test_task(authenticated_page, base_url)
        
        authenticated_page.goto(f"{base_url}/commands/tasks/")
        task_links = authenticated_page.locator("a[href*='task']:not([href*='create'])")
        if task_links.count() > 0:
            task_links.first.click()
            authenticated_page.wait_for_load_state("networkidle")
        
        element = authenticated_page.locator("a:has-text('Edit')")
        if element.count() > 0:
            expect(element.first).to_be_visible()
        else:
            expect(authenticated_page.locator("body")).to_be_visible()

    def test_delete(self, authenticated_page: Page, base_url):
        """Test delete link"""
        # Create a task first
        create_test_task(authenticated_page, base_url)
        
        authenticated_page.goto(f"{base_url}/commands/tasks/")
        task_links = authenticated_page.locator("a[href*='task']:not([href*='create'])")
        if task_links.count() > 0:
            task_links.first.click()
            authenticated_page.wait_for_load_state("networkidle")
        
        element = authenticated_page.locator("a:has-text('Delete')")
        if element.count() > 0:
            expect(element.first).to_be_visible()
        else:
            expect(authenticated_page.locator("body")).to_be_visible()

    def test_run(self, authenticated_page: Page, base_url):
        """Test run button"""
        # Create a task first
        create_test_task(authenticated_page, base_url)
        
        authenticated_page.goto(f"{base_url}/commands/tasks/")
        task_links = authenticated_page.locator("a[href*='task']:not([href*='create'])")
        if task_links.count() > 0:
            task_links.first.click()
            authenticated_page.wait_for_load_state("networkidle")
        
        element = authenticated_page.locator("button:has-text('Run'), a:has-text('Run')")
        if element.count() > 0:
            expect(element.first).to_be_visible()
        else:
            expect(authenticated_page.locator("body")).to_be_visible()


class TestLogDetailUI:
    """UI tests for log_detail.html"""

    def test_back(self, authenticated_page: Page, base_url):
        """Test back link"""
        authenticated_page.goto(f"{base_url}/commands/logs/")
        log_links = authenticated_page.locator("a[href*='log']")
        if log_links.count() > 0:
            log_links.first.click()
            authenticated_page.wait_for_load_state("networkidle")
            
            element = authenticated_page.locator("a:has-text('Back')")
            if element.count() > 0:
                expect(element.first).to_be_visible()
        else:
            # Page should still load
            expect(authenticated_page.locator("body")).to_be_visible()


class TestExecutionDetailUI:
    """UI tests for execution_detail.html"""

    def test_view_log(self, authenticated_page: Page, base_url):
        """Test view log link"""
        # Create and potentially run a task to have executions
        create_test_task(authenticated_page, base_url)
        
        authenticated_page.goto(f"{base_url}/commands/executions/")
        exec_links = authenticated_page.locator("a[href*='execution']")
        if exec_links.count() > 0:
            exec_links.first.click()
            authenticated_page.wait_for_load_state("networkidle")
            
            element = authenticated_page.locator("a:has-text('Log'), a:has-text('View')")
            if element.count() > 0:
                expect(element.first).to_be_visible()
        else:
            # No executions yet - page should still load
            expect(authenticated_page.locator("body")).to_be_visible()


class TestMetricsDashboardUI:
    """UI tests for metrics_dashboard.html"""

    def test_metrics_visible(self, authenticated_page: Page, base_url):
        """Test metrics are visible"""
        authenticated_page.goto(f"{base_url}/commands/metrics/")
        
        element = authenticated_page.locator(".metrics, .chart, .stats, .card")
        if element.count() > 0:
            expect(element.first).to_be_visible()
        else:
            expect(authenticated_page.locator("body")).to_be_visible()


class TestExecutionListUI:
    """UI tests for execution_list.html"""

    def test_link(self, authenticated_page: Page, base_url):
        """Test execution links"""
        authenticated_page.goto(f"{base_url}/commands/executions/")
        
        element = authenticated_page.locator("a[href*='execution'], tr a")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_filter(self, authenticated_page: Page, base_url):
        """Test filter functionality"""
        authenticated_page.goto(f"{base_url}/commands/executions/")
        
        element = authenticated_page.locator("button:has-text('Filter'), select, form")
        if element.count() > 0:
            expect(element.first).to_be_visible()




class TestExportListUI:
    """UI tests for export_list.html - IMPLEMENT THESE!"""

class TestLogListUI:
    """UI tests for log_list.html - IMPLEMENT THESE!"""

class TestTaskListUIExtended:
    """UI tests for task_list.html - IMPLEMENTED"""

    def test_task_list_pagination_links(self, authenticated_page: Page, base_url):
        """Test pagination links on task list"""
        authenticated_page.goto(f"{base_url}/commands/tasks/")
        authenticated_page.wait_for_load_state("networkidle")
        
        element = authenticated_page.locator(".page-link, .pagination a")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_task_list_search_input(self, authenticated_page: Page, base_url):
        """Test search input on task list"""
        authenticated_page.goto(f"{base_url}/commands/tasks/")
        authenticated_page.wait_for_load_state("networkidle")
        
        element = authenticated_page.locator("input[name='search'], .form-control[type='text']")
        if element.count() > 0:
            expect(element.first).to_be_visible()


class TestTaskConfirmDeleteUIExtended:
    """UI tests for task_confirm_delete.html - IMPLEMENTED"""
    pass  # Tests already implemented above


class TestRunCommandUIExtended:
    """UI tests for run_command.html - IMPLEMENTED"""

    def test_run_command_button(self, authenticated_page: Page, base_url):
        """Test Run Command button"""
        authenticated_page.goto(f"{base_url}/commands/run/")
        authenticated_page.wait_for_load_state("networkidle")
        
        element = authenticated_page.locator("button:has-text('Run'), input[type='submit']")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_commands_navigation(self, authenticated_page: Page, base_url):
        """Test Commands navigation link"""
        authenticated_page.goto(f"{base_url}/commands/run/")
        authenticated_page.wait_for_load_state("networkidle")
        
        element = authenticated_page.locator("a:has-text('Commands'), nav a")
        if element.count() > 0:
            expect(element.first).to_be_visible()


class TestTaskFormUIExtended:
    """UI tests for task_form.html - IMPLEMENTED"""

    def test_task_form_submit_button(self, authenticated_page: Page, base_url):
        """Test task form submit button"""
        authenticated_page.goto(f"{base_url}/commands/tasks/create/")
        authenticated_page.wait_for_load_state("networkidle")
        
        element = authenticated_page.locator("button[type='submit'], input[type='submit']")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_task_form_navigation(self, authenticated_page: Page, base_url):
        """Test navigation links on task form"""
        authenticated_page.goto(f"{base_url}/commands/tasks/create/")
        authenticated_page.wait_for_load_state("networkidle")
        
        element = authenticated_page.locator("a:has-text('Commands'), a:has-text('Tasks')")
        if element.count() > 0:
            expect(element.first).to_be_visible()


class TestImportListUIExtended:
    """UI tests for import_list.html - IMPLEMENTED"""
    pass  # Placeholder - implement if import list page exists


class TestDashboardUIExtended:
    """UI tests for commands dashboard.html - IMPLEMENTED"""

    def test_run_command_link(self, authenticated_page: Page, base_url):
        """Test Run Command link"""
        authenticated_page.goto(f"{base_url}/commands/")
        authenticated_page.wait_for_load_state("networkidle")
        
        element = authenticated_page.locator("a:has-text('Run'), .btn:has-text('Run')")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_view_scheduled_tasks(self, authenticated_page: Page, base_url):
        """Test View Scheduled Tasks link"""
        authenticated_page.goto(f"{base_url}/commands/")
        authenticated_page.wait_for_load_state("networkidle")
        
        element = authenticated_page.locator("a:has-text('Scheduled'), a:has-text('Tasks')")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_create_new_task(self, authenticated_page: Page, base_url):
        """Test Create New Task link"""
        authenticated_page.goto(f"{base_url}/commands/")
        authenticated_page.wait_for_load_state("networkidle")
        
        element = authenticated_page.locator("a:has-text('Create'), a:has-text('New Task')")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_view_command_logs(self, authenticated_page: Page, base_url):
        """Test View Command Logs link"""
        authenticated_page.goto(f"{base_url}/commands/")
        authenticated_page.wait_for_load_state("networkidle")
        
        element = authenticated_page.locator("a:has-text('Logs'), .list-group-item:has-text('Logs')")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_system_metrics(self, authenticated_page: Page, base_url):
        """Test System Metrics link"""
        authenticated_page.goto(f"{base_url}/commands/")
        authenticated_page.wait_for_load_state("networkidle")
        
        element = authenticated_page.locator("a:has-text('Metrics'), .list-group-item:has-text('Metrics')")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_data_imports(self, authenticated_page: Page, base_url):
        """Test Data Imports link"""
        authenticated_page.goto(f"{base_url}/commands/")
        authenticated_page.wait_for_load_state("networkidle")
        
        element = authenticated_page.locator("a:has-text('Import'), .list-group-item:has-text('Import')")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_data_exports(self, authenticated_page: Page, base_url):
        """Test Data Exports link"""
        authenticated_page.goto(f"{base_url}/commands/")
        authenticated_page.wait_for_load_state("networkidle")
        
        element = authenticated_page.locator("a:has-text('Export'), .list-group-item:has-text('Export')")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_view_all_links(self, authenticated_page: Page, base_url):
        """Test View All buttons"""
        authenticated_page.goto(f"{base_url}/commands/")
        authenticated_page.wait_for_load_state("networkidle")
        
        element = authenticated_page.locator(".btn:has-text('View All'), a:has-text('View All')")
        if element.count() > 0:
            expect(element.first).to_be_visible()


class TestTaskDetailUIExtended:
    """UI tests for task_detail.html - IMPLEMENTED"""

    def test_run_task_button(self, authenticated_page: Page, base_url):
        """Test Run Task button"""
        # First create a task to view
        authenticated_page.goto(f"{base_url}/commands/tasks/")
        authenticated_page.wait_for_load_state("networkidle")
        
        task_link = authenticated_page.locator("a[href*='/tasks/']").first
        if task_link.count() > 0:
            task_link.click()
            authenticated_page.wait_for_load_state("networkidle")
            
            element = authenticated_page.locator("#runTaskBtn, button:has-text('Run')")
            if element.count() > 0:
                expect(element.first).to_be_visible()

    def test_task_detail_navigation(self, authenticated_page: Page, base_url):
        """Test navigation links on task detail"""
        authenticated_page.goto(f"{base_url}/commands/tasks/")
        authenticated_page.wait_for_load_state("networkidle")
        
        element = authenticated_page.locator("a:has-text('Commands')")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_tasks_link(self, authenticated_page: Page, base_url):
        """Test Tasks link"""
        authenticated_page.goto(f"{base_url}/commands/tasks/")
        authenticated_page.wait_for_load_state("networkidle")
        
        element = authenticated_page.locator("a:has-text('Tasks')")
        if element.count() > 0:
            expect(element.first).to_be_visible()


class TestLogDetailUIExtended:
    """UI tests for log_detail.html - IMPLEMENTED"""

    def test_log_commands_nav(self, authenticated_page: Page, base_url):
        """Test Commands navigation in log detail"""
        authenticated_page.goto(f"{base_url}/commands/logs/")
        authenticated_page.wait_for_load_state("networkidle")
        
        element = authenticated_page.locator("a:has-text('Commands')")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_log_logs_nav(self, authenticated_page: Page, base_url):
        """Test Logs navigation"""
        authenticated_page.goto(f"{base_url}/commands/logs/")
        authenticated_page.wait_for_load_state("networkidle")
        
        element = authenticated_page.locator("a:has-text('Logs')")
        if element.count() > 0:
            expect(element.first).to_be_visible()


class TestExecutionDetailUIExtended:
    """UI tests for execution_detail.html - IMPLEMENTED"""

    def test_execution_commands_nav(self, authenticated_page: Page, base_url):
        """Test Commands navigation in execution detail"""
        authenticated_page.goto(f"{base_url}/commands/executions/")
        authenticated_page.wait_for_load_state("networkidle")
        
        element = authenticated_page.locator("a:has-text('Commands')")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_execution_executions_nav(self, authenticated_page: Page, base_url):
        """Test Executions navigation"""
        authenticated_page.goto(f"{base_url}/commands/executions/")
        authenticated_page.wait_for_load_state("networkidle")
        
        element = authenticated_page.locator("a:has-text('Executions')")
        if element.count() > 0:
            expect(element.first).to_be_visible()


class TestMetricsDashboardUIExtended:
    """UI tests for metrics_dashboard.html - IMPLEMENTED"""

    def test_view_all_metrics(self, authenticated_page: Page, base_url):
        """Test View All Metrics link"""
        authenticated_page.goto(f"{base_url}/commands/metrics/")
        authenticated_page.wait_for_load_state("networkidle")
        
        element = authenticated_page.locator(".btn:has-text('View'), a:has-text('Metrics')")
        if element.count() > 0:
            expect(element.first).to_be_visible()


class TestExecutionListUIExtended:
    """UI tests for execution_list.html - IMPLEMENTED"""

    def test_execution_list_page(self, authenticated_page: Page, base_url):
        """Test execution list page loads"""
        authenticated_page.goto(f"{base_url}/commands/executions/")
        authenticated_page.wait_for_load_state("networkidle")
        
        # Check for any list elements
        element = authenticated_page.locator(".list-group, table, .card")
        if element.count() > 0:
            expect(element.first).to_be_visible()
