"""
UI Tests for api_app - Django Test Enforcer
Generated on: 2026-02-07 20:31:33

These tests implement the stubs generated by django-test-enforcer.
Uses Playwright for browser automation.

Run with: pytest api_app/test_ui.py --headed
"""
import pytest
from playwright.sync_api import Page, expect


class TestDashboardUI:
    """UI tests for dashboard.html"""

    def test_swagger_docs(self, page: Page, base_url):
        """Test link: Swagger Docs"""
        page.goto(f"{base_url}/api/", timeout=60000)
        page.wait_for_load_state("networkidle")
        
        element = page.locator("a:has-text('Swagger'), a[href*='swagger']")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_re_doc(self, page: Page, base_url):
        """Test link: ReDoc"""
        page.goto(f"{base_url}/api/", timeout=60000)
        page.wait_for_load_state("networkidle")
        
        element = page.locator("a:has-text('ReDoc'), a[href*='redoc']")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_view_all(self, page: Page, base_url):
        """Test link: View All"""
        page.goto(f"{base_url}/api/", timeout=60000)
        page.wait_for_load_state("networkidle")
        
        element = page.locator("a:has-text('View All')")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_api_root(self, page: Page, base_url):
        """Test link: API Root"""
        page.goto(f"{base_url}/api/", timeout=60000)
        page.wait_for_load_state("networkidle")
        
        element = page.locator("a:has-text('API Root'), a[href*='api-root']")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_products_api(self, page: Page, base_url):
        """Test link: Products API"""
        page.goto(f"{base_url}/api/", timeout=60000)
        page.wait_for_load_state("networkidle")
        
        element = page.locator("a:has-text('Products'), a[href*='products']")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_reviews_api(self, page: Page, base_url):
        """Test link: Reviews API"""
        page.goto(f"{base_url}/api/", timeout=60000)
        page.wait_for_load_state("networkidle")
        
        element = page.locator("a:has-text('Reviews'), a[href*='reviews']")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_users_api(self, page: Page, base_url):
        """Test link: Users API"""
        page.goto(f"{base_url}/api/", timeout=60000)
        page.wait_for_load_state("networkidle")
        
        element = page.locator("a:has-text('Users'), a[href*='users']")
        if element.count() > 0:
            expect(element.first).to_be_visible()


class TestSwaggerUI:
    """UI tests for Swagger documentation"""

    def test_swagger_page_loads(self, page: Page, base_url):
        """Test Swagger UI page loads"""
        page.goto(f"{base_url}/swagger/", timeout=60000)
        page.wait_for_load_state("networkidle")
        
        element = page.locator(".swagger-ui, #swagger-ui")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_swagger_info(self, page: Page, base_url):
        """Test Swagger info section"""
        page.goto(f"{base_url}/swagger/", timeout=60000)
        page.wait_for_load_state("networkidle")
        
        element = page.locator(".info, .info-title")
        if element.count() > 0:
            expect(element.first).to_be_visible()


class TestReDocUI:
    """UI tests for ReDoc documentation"""

    def test_redoc_page_loads(self, page: Page, base_url):
        """Test ReDoc page loads"""
        page.goto(f"{base_url}/redoc/", timeout=60000)
        page.wait_for_load_state("networkidle")
        
        element = page.locator("redoc, .redoc-wrap")
        if element.count() > 0:
            expect(element.first).to_be_visible()


class TestAPIRootUI:
    """UI tests for API Root browsable interface"""

    def test_api_root_loads(self, page: Page, base_url):
        """Test API root page loads"""
        page.goto(f"{base_url}/api/v1/", timeout=60000)
        page.wait_for_load_state("networkidle")
        
        # DRF browsable API
        element = page.locator(".api-root, pre, .response-info")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_endpoints_visible(self, page: Page, base_url):
        """Test API endpoints are visible"""
        page.goto(f"{base_url}/api/v1/", timeout=60000)
        page.wait_for_load_state("networkidle")
        
        # Check for links to API endpoints
        element = page.locator("a[href*='api']")
        if element.count() > 0:
            expect(element.first).to_be_visible()


class TestDashboardUIExtended:
    """UI tests for dashboard.html - IMPLEMENTED"""

    def test_view_all_link(self, page: Page, base_url):
        """Test link: View All →"""
        page.goto(f"{base_url}/api/", timeout=60000)
        page.wait_for_load_state("networkidle")
        
        element = page.locator("a:has-text('View All'), .text-dark")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_orders_api(self, page: Page, base_url):
        """Test link: Orders API"""
        page.goto(f"{base_url}/api/", timeout=60000)
        page.wait_for_load_state("networkidle")
        
        element = page.locator("a:has-text('Orders'), .list-group-item:has-text('Orders')")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_health_check(self, page: Page, base_url):
        """Test link: Health Check"""
        page.goto(f"{base_url}/api/", timeout=60000)
        page.wait_for_load_state("networkidle")
        
        element = page.locator("a:has-text('Health'), .list-group-item:has-text('Health')")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_global_search(self, page: Page, base_url):
        """Test link: Global Search"""
        page.goto(f"{base_url}/api/", timeout=60000)
        page.wait_for_load_state("networkidle")
        
        element = page.locator("a:has-text('Search'), .list-group-item:has-text('Search')")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_products_gallery(self, page: Page, base_url):
        """Test link: Products Gallery"""
        page.goto(f"{base_url}/api/", timeout=60000)
        page.wait_for_load_state("networkidle")
        
        element = page.locator("a:has-text('Products'), .list-group-item:has-text('Products')")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_orders_list(self, page: Page, base_url):
        """Test link: Orders List"""
        page.goto(f"{base_url}/api/", timeout=60000)
        page.wait_for_load_state("networkidle")
        
        element = page.locator("a:has-text('Orders List'), .list-group-item:has-text('Orders')")
        if element.count() > 0:
            expect(element.first).to_be_visible()

    def test_dashboard_links_visible(self, page: Page, base_url):
        """Test that dashboard has navigation links"""
        page.goto(f"{base_url}/api/", timeout=60000)
        page.wait_for_load_state("networkidle")
        
        element = page.locator(".btn, a.list-group-item")
        if element.count() > 0:
            expect(element.first).to_be_visible()
